services:
  database:
    image: postgres:17
    container_name: timescaledb
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timescaledb
    volumes:
      - type: volume
        source: timescale_volume
        target: /var/lib/postgresql/data
        read_only: false
    networks:
      - timescale_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
networks:
  timescale_network:

volumes:
  timescale_volume:
