services:
  database:
    image: postgres:17
    container_name: timescaledb
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: volume
        source: timescale_volume
        target: /var/lib/postgresql/data
        read_only: false
    networks:
      - timescale_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  FastAPI:
    container_name: FastAPI
    image: ouslan/jp-api:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 8051:8000
    networks:
      - timescale_network
    depends_on:
      database:
        condition: service_healthy
networks:
  timescale_network:

volumes:
  timescale_volume:
